* title
  - Note taken on [2012-02-09 四 20:31] \\
	use #+TITLE: This is the title
* table-of-content
  - Note taken on [2012-02-09 四 20:35] \\
	eg. #+OPTIONS: skip:t
	eg. #+TEXT: This text will go before the *first* headline.
	eg. #+TEXT: [TABLE-OF-CONTENTS]
	eg. #+TEXT: This goes between the table of contents and the *first* headline
* insert template with export options
  - Note taken on [2012-02-09 四 20:45] \\
	C-c C-e t
* view
  - Note taken on [2012-02-09 四 19:54] \\
	C-c /
* add a time-stamped note
  - Note taken on [2012-02-09 四 19:37] \\
	C-c C-z add a time-stamped note
	finish with C-c C-c, cancel with C-c C-k
* 创建注解
  - Note taken on [2012-02-09 四 19:43] \\
	[1] [fn:name] [fn::inline] [fn:name:a definition]
	and C-c C-x f
* 表格
  - Note taken on [2012-02-09 四 19:46] \\
	C-c | NxN 创建N行N列表格
* 插入链接
  - Note taken on [2012-02-09 四 19:51] \\
	C-c C-l [[][]]
* 插入TODO
  - Note taken on [2012-02-09 四 19:54] \\
	C-c C-t or C-u C-c C-t
* 搜索TODO（当前文件）
  - Note taken on [2012-02-09 四 19:56] \\
	C-c / t
* 搜索TODO（全局）
  - Note taken on [2012-02-09 四 19:56] \\
	C-c a t
* 创建TODO
  - Note taken on [2012-02-09 四 19:57] \\
	S-M-RET
* 配置TODO
  - Note taken on [2012-02-09 四 19:58] \\
	(setq org-todo-keywords
	'((sequence "TODO" "FEEDBACK" "VERIFY" "|" "DONE" "DELEGATED")))
* 配置TODO状态
  - Note taken on [2012-02-09 四 20:01] \\
	(setq org-todo-keywords '((type "Fred" "Sara" "Lucy" "|" "DONE")))
* 配置多关键字TODO
  - Note taken on [2012-02-09 四 20:02] \\
	(setq org-todo-keywords
	'((sequence "TODO" "|" "DONE")
	(sequence "REPORT" "BUG" "KNOWNCAUSE" "|" "FIXED")
	(sequence "|" "CANCELED")))
* 配置TODO关键字
  - Note taken on [2012-02-09 四 20:02] \\
	(setq org-todo-keywords
	'((sequence "TODO(t)" "|" "DONE(d)")
	(sequence "REPORT(r)" "BUG(b)" "KNOWNCAUSE(k)" "|" "FIXED(f)")
	(sequence "|" "CANCELED(c)")))
* 配置单独文件TODO
  - Note taken on [2012-02-09 四 20:04] \\
	like #+TODO: TODO FEEDBACK VERIFY | DONE CANCELED
	like #+TYP_TODO: Fred Sara Lucy Mike | DONE
	like #+TODO: TODO | DONE
	like #+TODO: REPORT BUG KNOWNCAUSE | FIXED
	like #+TODO: | CANCELED
* 配置TODO颜色、字体
  - Note taken on [2012-02-09 四 20:05] \\
	(setq org-todo-keyword-faces
	'(("TODO" . org-warning) ("STARTED" . "yellow")
	("CANCELED" . (:foreground "blue" :weight bold))))
* create time or date
  - Note taken on [2012-02-09 四 20:23] \\
	C-c . or C-c ! or C-u C-c . or C-u C-c !
	or C-c C-c or C-c < or C-c > or C-c C-o
    or C-c C-x C-t
* insert deadline or schedules
  - Note taken on [2012-02-09 四 20:25] \\
	C-c C-d and C-c C-s
	C-c C-x C-k
	C-c / d
	C-c / b
	C-c / a
* clocking work time
  - Note taken on [2012-02-09 四 20:26] \\
	config:
	(setq org-clock-persist 'history)
	(org-clock-persistence-insinuate)
	command:
	C-c C-x C-i
	C-c C-x C-o
	C-c C-x C-e
	C-c C-c or C-c C-y
* capture
  - Note taken on [2012-02-09 四 20:28] \\
	(setq org-default-notes-file (concat org-directory "/notes.org"))
	(define-key global-map "\C-cc" 'org-capture)
	
	C-c c
	C-c C-c
	C-c C-w 
	C-c C-k
	C-u C-c c
	C-u C-u C-c c
	(setq org-capture-templates
    '(("t" "Todo" entry (file+headline "~/org/gtd.org" "Tasks")
           "* TODO %?\n %i\n %a")
      ("j" "Journal" entry (file+datetree "~/org/journal.org")
           "* %?\nEntered on %U\n %i\n %a")))
	(define-key global-map "\C-cx"
       (lambda () (interactive) (org-capture nil "x")))
